services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ticketing.jimmycorp.org`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    build:
      context: ./TicketChallengerServer
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=production
      - CLIENT_URL=https://ticketing.jimmycorp.org
