services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./TicketChallengerServer
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=production
      - CLIENT_URL=https://ticketing.jimmycorp.org
